# Expirements for the Image Sticthing App

In [90]:
import cv2 
import numpy as np
import pandas as pd
import sticth_app

## Critical Stepps
1. Get All Features Into a Table

In [91]:
col_names = np.array(["Id", "Descriptor", "ImgId", "MatchId"])
print(col_names)

img_paths = sticth_app.get_image_files("/home/schmidtg/coding_projetcs/local-image-features-apps/image-stitching/datasets/example-data/flower")
orb = cv2.ORB_create()

N = 0
des = np.empty((0,32))
img_ids = np.empty((0))

for img_id, img_path in enumerate(img_paths): 
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    kp_new, des_new = orb.detectAndCompute(img, None)  # type: ignore
    des = np.vstack((des, des_new))
    N_new = len(des_new)
    N += N_new
    img_ids_new = np.full((N_new), img_id+1)
    img_ids = np.concatenate((img_ids, img_ids_new), axis=0)
    
kp_ids = np.arange(1, N+1)

['Id' 'Descriptor' 'ImgId' 'MatchId']


In [92]:
img_ids

array([1., 1., 1., ..., 4., 4., 4.], shape=(2000,))

In [93]:
des

array([[ 57., 151.,  87., ..., 142., 240., 217.],
       [ 57., 241., 106., ..., 130., 110., 233.],
       [ 17., 137., 194., ..., 136., 177., 136.],
       ...,
       [184.,  75.,  74., ...,  59., 126., 138.],
       [101.,  32., 128., ..., 121., 122., 130.],
       [ 66., 154.,  42., ...,   4.,  45.,  95.]], shape=(2000, 32))

In [94]:
kp_ids

array([   1,    2,    3, ..., 1998, 1999, 2000], shape=(2000,))